# Generated by Django 5.0.7 on 2024-07-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standart_Coin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.DecimalField(decimal_places=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name_id', models.TextField()),
                ('key_one', models.TextField()),
                ('key_two', models.TextField(blank=True, null=True)),
                ('encrypted_coin_str', models.TextField()),
                ('encrypted_coin', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('encrypted_coin', models.TextField()),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.TextField()),
                ('encrypted_coin', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
