# Generated by Django 4.2.14 on 2024-08-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongregateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_inputs', models.IntegerField()),
                ('coins_encrypted', models.TextField()),
                ('keys_encrypted', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user_info',
            name='wallet',
            field=models.TextField(default='default'),
        ),
    ]
